version: 2.0
jobs:
  build:
    working_directory: ~/hw-prim
    docker:
      - image: fpco/stack-build:latest

    steps:
      - checkout

      - run:
          name: Copying scripts
          command: |
            mkdir -p ~/.local/bin
            cp ./scripts/* ~/.local/bin
            fetch

      ##### Building library
      - restore_cache:
          keys:
            - dot-stack-{{ checksum "stack.yaml" }}-{{ checksum "hw-prim.cabal" }}
            - dot-stack-{{ checksum "stack.yaml" }}-build
            - dot-stack-{{ checksum "stack.yaml" }}-setup

      - restore_cache:
          key: dot-stack-work-{{ checksum "stack.yaml" }}

      - run:
          name: Stack setup
          command: stack setup

      - save_cache:
          key: dot-stack-{{ checksum "stack.yaml" }}-setup
          paths:
            - ~/.stack

      - run:
          name: Building dependencies
          command: stack build --only-dependencies

      - run:
          name: Compiling
          command: stack build --test --no-run-tests

      - save_cache:
          key: dot-stack-{{ checksum "stack.yaml" }}-{{ checksum "hw-prim.cabal" }}
          paths:
            - ~/.stack
      - save_cache:
          key: dot-stack-{{ checksum "stack.yaml" }}-build
          paths:
            - ~/.stack

      - save_cache:
          key: dot-stack-work-{{ checksum "stack.yaml" }}
          paths: ~/hw-prim/.stack-work

      ##### Running tests
      - run:
          name: Running tests
          command: stack test

      - deploy:
          command: |
            if [ "$CIRCLE_PROJECT_USERNAME" == "haskell-works" ]; then
              if [[ "$CIRCLE_BRANCH" =~ .*-branch ]]; then
                when tag autotag
              elif [[ "$CIRCLE_BRANCH" =~ v.* ]]; then
                publish
              fi
            fi
deployment:
  tagged_builds:
    tag: /v.*/
    commands:
      - echo "Make tags run in 2.0"
