name: hw-prim
version: '0.6.2.0'
synopsis: Primitive functions and data types
description: Primitive functions and data types.
category: Data
author: John Ky
maintainer: newhoggy@gmail.com
copyright: 2016-2018 John Ky
license: BSD3
github: haskell-works/hw-prim
homepage: http://github.com/haskell-works/hw-prim#readme
extra-source-files:
- README.md
other-extensions: AllowAmbiguousTypes
ghc-options: -Wall
tested-with: GHC == 8.4.2, GHC == 8.2.2, GHC == 8.0.2, GHC == 7.10.3
dependencies:
- base >=4.8 && <5
- bytestring >= 0.9 && < 0.11
- mmap >= 0.5 && < 0.6
- vector >= 0.12 && < 0.13
- transformers >= 0.4 && < 0.6

library:
  source-dirs: src
  ghc-options:
  - -O2
  - -msse4.2
  exposed-modules:
  - HaskellWorks.Data.AtIndex
  - HaskellWorks.Data.ByteString
  - HaskellWorks.Data.Char.IsChar
  - HaskellWorks.Data.Concat
  - HaskellWorks.Data.Container
  - HaskellWorks.Data.Decode
  - HaskellWorks.Data.Drop
  - HaskellWorks.Data.Empty
  - HaskellWorks.Data.Filter
  - HaskellWorks.Data.FromByteString
  - HaskellWorks.Data.FromForeignRegion
  - HaskellWorks.Data.Generate
  - HaskellWorks.Data.Head
  - HaskellWorks.Data.Length
  - HaskellWorks.Data.Naive
  - HaskellWorks.Data.Positioning
  - HaskellWorks.Data.Product
  - HaskellWorks.Data.Search
  - HaskellWorks.Data.Sign
  - HaskellWorks.Data.Snoc
  - HaskellWorks.Data.Take
  - HaskellWorks.Data.TreeCursor
  - HaskellWorks.Data.Uncons
  - HaskellWorks.Data.Unsign
  - HaskellWorks.Data.Vector.AsVector64
  - HaskellWorks.Data.Vector.AsVector64s
  - HaskellWorks.Data.Vector.BoxedVectorLike
  - HaskellWorks.Data.Vector.StorableVectorLike

tests:
  hw-prim-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck >= 2.10 && < 2.12
    - directory >= 1.2 && < 1.4
    - exceptions >= 0.8 && < 0.11
    - hedgehog >= 0.5 && < 0.7
    - hspec >= 2.4 && <2.6
    - hw-hspec-hedgehog >= 0.1 && < 0.2
    - hw-prim
    verbatim:
      build-tool-depends: hspec-discover:hspec-discover

benchmarks:
  bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -O2
    - -msse4.2
    dependencies:
    - criterion >= 1.2 && < 1.5
    - hw-prim
    - mmap >= 0.5 && < 0.6

stability: Experimental

when:
- condition: flag(bounds-checking-enabled)
  cpp-options:
  - -DBOUNDS_CHECKING_ENABLED

flags:
  bounds-checking-enabled:
    description: Enable bmi2 instruction set
    manual: false
    default: false
